services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - learnfinity-app-network
    volumes:
      - /home/admin/Documents/learnfinity/db:/data/db

  react:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      - mongodb
    networks:
      - learnfinity-app-network
    volumes:
      - build-volume:/usr/src/app/build
    env_file:
      - ./client/.env

  express:
    build:
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    depends_on:
      - mongodb
      - react
    networks:
      - learnfinity-app-network
    ports:
      - "8000:8000"
    volumes:
      - build-volume:/usr/src/app/public

networks:
  learnfinity-app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
  build-volume:
    driver: local
