import { UseAddEditLearningPathRelatedItemModalContainerType } from './useAddEditLearningPathRelatedItemModalContainer';

export type IAddEditLearningPathRelatedItemModalProps = UseAddEditLearningPathRelatedItemModalContainerType;
