name: Deploy to Server

on:
  pull:
    branches:
      - main

env:
  SERVER_HOST: ${{ secrets.SERVER_HOST }}
  SERVER_USER: ${{ secrets.SERVER_USER }}
  SERVER_SSH_KEY: ${{ secrets.SERVER_SSH_KEY }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            cd /app
            if [ -f docker-compose.yml ]; then
              mkdir -p /backup
              cp docker-compose.yml /backup/docker-compose-prev.yml
            fi
            git pull origin main
            docker-compose up --build -d

            
        #Rollback if http response is not 200   
      - name: Health Check
        run: |
          STATUS_CODE=$(curl -o /dev/null -s -w "%{http_code}\n" http://your-app-url)
          if [ $STATUS_CODE -ne 200 ]; then
            echo "Health check failed, rolling back to previous version"
            ssh -o StrictHostKeyChecking=no -i ${{ secrets.SERVER_SSH_KEY }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << EOF
              cd /app
              if [ -f /backup/docker-compose-prev.yml ]; then
                docker-compose -f /backup/docker-compose-prev.yml up -d
              else
                echo "No previous version to roll back to"
              fi
            EOF
            exit 1
          fi
